## cat docker-compose.yml
#version: '3.3'
#services:
#  ### MySQL Container
#  mysql:
#    build:
#      args:
#        - MYSQL_DATABASE=${MYSQL_DATABASE}
#        - MYSQL_USER=${MYSQL_USER}
#        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#    ports:
#      - "${MYSQL_PORT}:3306"
#
##  app:
##    build:
##      context: .
##      dockerfile: Dockerfile
##    ports:
##      - "8080:8080"
##    depends_on:
##      - mysql

version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/igse?useSSL=false
      SPRING_DATASOURCE_USERNAME: igse
      SPRING_DATASOURCE_PASSWORD: salam123

  db:
    image: mysql:latest
    restart: always
    container_name: db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
